packages:
  - apps/*
  - apps/*/web
  - packages/*
  - packages/*/example
allowBuilds:
  '@firebase/util': true
  '@sentry/cli': true
  esbuild: true
  lefthook: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - expo-eas-client@57.0.3
  - expo-updates@57.0.21
  - lucide-react@1.39.0
patchedDependencies:
  '@ark/schema': patches/@ark__schema.patch
  metro-runtime@0.84.5: patches/metro-runtime@0.84.5.patch
  metro@0.84.5: patches/metro@0.84.5.patch
  rn-newarch-svga-player@1.1.16: patches/rn-newarch-svga-player@1.1.16.patch
