packages:
  - apps/*
  - packages/*
  - packages/*/example

onlyBuiltDependencies:
  - '@evilmartians/lefthook'
  - '@firebase/util'
  - '@sentry/cli'
  - '@shopify/react-native-skia'
  - esbuild
  - lefthook
  - protobufjs
  - react-native-logs
  - sharp
  - unrs-resolver
  - workerd
patchedDependencies:
  expo-modules-core@56.0.17: patches/expo-modules-core@56.0.17.patch
